#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Dec 13 20:39:53 CST 2019
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim cpu_sim_behav -key {Behavioral:sim_1:Functional:cpu_sim} -tclbatch cpu_sim.tcl -log simulate.log"
xsim cpu_sim_behav -key {Behavioral:sim_1:Functional:cpu_sim} -tclbatch cpu_sim.tcl -log simulate.log

