# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.cache/wt [current_project]
set_property parent.project_path /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.runs/cpu_synth_1/cpu.dcp
set_property used_in_implementation false [get_files /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.runs/cpu_synth_1/cpu.dcp]
add_files -quiet /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.runs/memory_synth_1/memory.dcp
set_property used_in_implementation false [get_files /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.runs/memory_synth_1/memory.dcp]
add_files -quiet /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.runs/counter_synth_1/counter.dcp
set_property used_in_implementation false [get_files /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.runs/counter_synth_1/counter.dcp]
add_files -quiet /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.runs/PS2Receiver_synth_1/PS2Receiver.dcp
set_property used_in_implementation false [get_files /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.runs/PS2Receiver_synth_1/PS2Receiver.dcp]
add_files -quiet /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.runs/uart_tx_synth_1/uart_tx.dcp
set_property used_in_implementation false [get_files /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.runs/uart_tx_synth_1/uart_tx.dcp]
add_files -quiet /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.runs/uart_buf_con_synth_1/uart_buf_con.dcp
set_property used_in_implementation false [get_files /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.runs/uart_buf_con_synth_1/uart_buf_con.dcp]
read_verilog -library xil_defaultlib {
  /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.srcs/sources_1/imports/hdl/Basys3_Abacus_Top.v
  /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.srcs/sources_1/imports/hdl/bin2ascii.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.srcs/constrs_1/imports/constraints/Basys3_Master.xdc
set_property used_in_implementation false [get_files /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.srcs/constrs_1/imports/constraints/Basys3_Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Basys3_Abacus_Top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Basys3_Abacus_Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Basys3_Abacus_Top_utilization_synth.rpt -pb Basys3_Abacus_Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
