#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Dec 13 21:49:44 CST 2019
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 1e80d9bf65a34994930614044d29ffbd --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L secureip --snapshot cpu_sim_func_impl xil_defaultlib.cpu_sim xil_defaultlib.glbl -log elaborate.log"
xelab -wto 1e80d9bf65a34994930614044d29ffbd --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L secureip --snapshot cpu_sim_func_impl xil_defaultlib.cpu_sim xil_defaultlib.glbl -log elaborate.log

