# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
set_param project.vivado.isBlockSynthRun true
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.cache/wt [current_project]
set_property parent.project_path /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.srcs/sources_1/imports/hdl/alu.v
  /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.srcs/sources_1/imports/hdl/pipe_controller.v
  /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.srcs/sources_1/imports/hdl/register.v
  /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.srcs/sources_1/imports/hdl/cpu.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc -mode out_of_context /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.srcs/cpu/new/cpu_ooc.xdc
set_property used_in_implementation false [get_files /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.srcs/cpu/new/cpu_ooc.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top cpu -part xc7a35tcpg236-1 -mode out_of_context

rename_ref -prefix_all cpu_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cpu.dcp
create_report "cpu_synth_1_synth_report_utilization_0" "report_utilization -file cpu_utilization_synth.rpt -pb cpu_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
