webtalk_init -webtalk_dir /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.sim/sim_1/synth/func/xsim/xsim.dir/cpu_sim_func_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Dec 13 21:50:31 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f9c091c3-0dd3-4836-9932-5ea77c74a50e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1e80d9bf65a34994930614044d29ffbd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "ManjaroLinux" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Manjaro Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2415.200 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "7.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "4740 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.18_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "199740_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1053167766 -regid "" -xml /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.sim/sim_1/synth/func/xsim/xsim.dir/cpu_sim_func_synth/webtalk/usage_statistics_ext_xsim.xml -html /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.sim/sim_1/synth/func/xsim/xsim.dir/cpu_sim_func_synth/webtalk/usage_statistics_ext_xsim.html -wdm /home/zekin/Code/ComputerOrganization/vivado/Basys3_CPU/Basys3_CPU.sim/sim_1/synth/func/xsim/xsim.dir/cpu_sim_func_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
